# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc_pb2 as rpc__pb2


class RPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPassengerNum = channel.unary_unary(
                '/rpc.RPC/GetPassengerNum',
                request_serializer=rpc__pb2.GPNRequest.SerializeToString,
                response_deserializer=rpc__pb2.GPNReply.FromString,
                )
        self.ReducePassengerNum = channel.unary_unary(
                '/rpc.RPC/ReducePassengerNum',
                request_serializer=rpc__pb2.RPNRequest.SerializeToString,
                response_deserializer=rpc__pb2.RPNReply.FromString,
                )


class RPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPassengerNum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReducePassengerNum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPassengerNum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPassengerNum,
                    request_deserializer=rpc__pb2.GPNRequest.FromString,
                    response_serializer=rpc__pb2.GPNReply.SerializeToString,
            ),
            'ReducePassengerNum': grpc.unary_unary_rpc_method_handler(
                    servicer.ReducePassengerNum,
                    request_deserializer=rpc__pb2.RPNRequest.FromString,
                    response_serializer=rpc__pb2.RPNReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.RPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPassengerNum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.RPC/GetPassengerNum',
            rpc__pb2.GPNRequest.SerializeToString,
            rpc__pb2.GPNReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReducePassengerNum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.RPC/ReducePassengerNum',
            rpc__pb2.RPNRequest.SerializeToString,
            rpc__pb2.RPNReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
