# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x03rpc\",\n\nRpcRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08stop_num\x18\x02 \x01(\t\"\x17\n\x08RpcReply\x12\x0b\n\x03num\x18\x01 \x01(\t22\n\x03RPC\x12+\n\x07get_num\x12\x0f.rpc.RpcRequest\x1a\r.rpc.RpcReply\"\x00\x42(\n\x14io.grpc.examples.rpcB\x08RpcProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\024io.grpc.examples.rpcB\010RpcProtoP\001\242\002\003HLW'
    _RPCREQUEST._serialized_start = 18
    _RPCREQUEST._serialized_end = 62
    _RPCREPLY._serialized_start = 64
    _RPCREPLY._serialized_end = 87
    _RPC._serialized_start = 89
    _RPC._serialized_end = 139
# @@protoc_insertion_point(module_scope)
