// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: grpc/proto/station.proto

package stationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationId int32 `protobuf:"varint,1,opt,name=stationId,proto3" json:"stationId,omitempty"`
}

func (x *GPNRequest) Reset() {
	*x = GPNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_station_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPNRequest) ProtoMessage() {}

func (x *GPNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_station_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPNRequest.ProtoReflect.Descriptor instead.
func (*GPNRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_station_proto_rawDescGZIP(), []int{0}
}

func (x *GPNRequest) GetStationId() int32 {
	if x != nil {
		return x.StationId
	}
	return 0
}

type GPNReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassagerNum int32 `protobuf:"varint,1,opt,name=passagerNum,proto3" json:"passagerNum,omitempty"`
}

func (x *GPNReply) Reset() {
	*x = GPNReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_station_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPNReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPNReply) ProtoMessage() {}

func (x *GPNReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_station_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPNReply.ProtoReflect.Descriptor instead.
func (*GPNReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_station_proto_rawDescGZIP(), []int{1}
}

func (x *GPNReply) GetPassagerNum() int32 {
	if x != nil {
		return x.PassagerNum
	}
	return 0
}

type RPNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationId  int32 `protobuf:"varint,1,opt,name=stationId,proto3" json:"stationId,omitempty"`
	BoarderNum int32 `protobuf:"varint,2,opt,name=boarderNum,proto3" json:"boarderNum,omitempty"`
}

func (x *RPNRequest) Reset() {
	*x = RPNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_station_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPNRequest) ProtoMessage() {}

func (x *RPNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_station_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPNRequest.ProtoReflect.Descriptor instead.
func (*RPNRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_station_proto_rawDescGZIP(), []int{2}
}

func (x *RPNRequest) GetStationId() int32 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *RPNRequest) GetBoarderNum() int32 {
	if x != nil {
		return x.BoarderNum
	}
	return 0
}

type RPNReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok int32 `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *RPNReply) Reset() {
	*x = RPNReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_station_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPNReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPNReply) ProtoMessage() {}

func (x *RPNReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_station_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPNReply.ProtoReflect.Descriptor instead.
func (*RPNReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_station_proto_rawDescGZIP(), []int{3}
}

func (x *RPNReply) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

var File_grpc_proto_station_proto protoreflect.FileDescriptor

var file_grpc_proto_station_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x0a, 0x47, 0x50, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x2c, 0x0a, 0x08, 0x47, 0x50, 0x4e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x4a, 0x0a,
	0x0a, 0x52, 0x50, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x1a, 0x0a, 0x08, 0x52, 0x50, 0x4e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x96, 0x01, 0x0a, 0x19, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x50, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x50, 0x4e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x11, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x50, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x50, 0x4e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_station_proto_rawDescOnce sync.Once
	file_grpc_proto_station_proto_rawDescData = file_grpc_proto_station_proto_rawDesc
)

func file_grpc_proto_station_proto_rawDescGZIP() []byte {
	file_grpc_proto_station_proto_rawDescOnce.Do(func() {
		file_grpc_proto_station_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_station_proto_rawDescData)
	})
	return file_grpc_proto_station_proto_rawDescData
}

var file_grpc_proto_station_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_proto_station_proto_goTypes = []interface{}{
	(*GPNRequest)(nil), // 0: station.GPNRequest
	(*GPNReply)(nil),   // 1: station.GPNReply
	(*RPNRequest)(nil), // 2: station.RPNRequest
	(*RPNReply)(nil),   // 3: station.RPNReply
}
var file_grpc_proto_station_proto_depIdxs = []int32{
	0, // 0: station.StationPassagerNumService.GetPassagerNum:input_type -> station.GPNRequest
	2, // 1: station.StationPassagerNumService.ReducePassagerNum:input_type -> station.RPNRequest
	1, // 2: station.StationPassagerNumService.GetPassagerNum:output_type -> station.GPNReply
	3, // 3: station.StationPassagerNumService.ReducePassagerNum:output_type -> station.RPNReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_station_proto_init() }
func file_grpc_proto_station_proto_init() {
	if File_grpc_proto_station_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_station_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_station_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPNReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_station_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_station_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPNReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_station_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_station_proto_goTypes,
		DependencyIndexes: file_grpc_proto_station_proto_depIdxs,
		MessageInfos:      file_grpc_proto_station_proto_msgTypes,
	}.Build()
	File_grpc_proto_station_proto = out.File
	file_grpc_proto_station_proto_rawDesc = nil
	file_grpc_proto_station_proto_goTypes = nil
	file_grpc_proto_station_proto_depIdxs = nil
}
