# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x03rpc\"\x1f\n\nGPNRequest\x12\x11\n\tstationId\x18\x01 \x01(\x05\" \n\x08GPNReply\x12\x14\n\x0cpassengerNum\x18\x01 \x01(\x05\"3\n\nRPNRequest\x12\x11\n\tstationId\x18\x01 \x01(\x05\x12\x12\n\nboarderNum\x18\x02 \x01(\x05\"\x16\n\x08RPNReply\x12\n\n\x02ok\x18\x01 \x01(\x05\x32r\n\x03RPC\x12\x33\n\x0fGetPassengerNum\x12\x0f.rpc.GPNRequest\x1a\r.rpc.GPNReply\"\x00\x12\x36\n\x12ReducePassengerNum\x12\x0f.rpc.RPNRequest\x1a\r.rpc.RPNReply\"\x00\x42(\n\x14io.grpc.examples.rpcB\x08RpcProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024io.grpc.examples.rpcB\010RpcProtoP\001\242\002\003HLW'
  _GPNREQUEST._serialized_start=18
  _GPNREQUEST._serialized_end=49
  _GPNREPLY._serialized_start=51
  _GPNREPLY._serialized_end=83
  _RPNREQUEST._serialized_start=85
  _RPNREQUEST._serialized_end=136
  _RPNREPLY._serialized_start=138
  _RPNREPLY._serialized_end=160
  _RPC._serialized_start=162
  _RPC._serialized_end=276
# @@protoc_insertion_point(module_scope)
